stages:
  - build
  - test
  - deploy
  - Trigger-cross-projects

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

build:linux:
  stage: build
  tags:
    - linux
  image: continuumio/miniconda3:latest
  script:
    - source activate
    - conda install mamba=$MAMBA_VERSION boa conda-verify -c conda-forge
    - echo $CONDARC > ~/.condarc
    - conda mambabuild conda-recipe --output-folder bld-dir
  artifacts:
    expire_in: 7 days
    paths:
      - bld-dir/

test:linux:
  variables:
    MINICONDA_OS: "Linux"
  stage: test
  tags:
    - linux
  image: continuumio/miniconda3:latest
  before_script:
    # Issue with OpenGL and X11 display
    # See: https://stackoverflow.com/questions/65675765/is-it-possible-to-run-x11-on-gitlab-ci
    # See: https://github.com/conda-forge/pygridgen-feedstock/issues/10
    # procps is used to grep the process by name to kill it when needed
    - apt update -yq
    - apt install -yq xorg-dev libglu1-mesa libgl1-mesa-dev xvfb libxinerama1 libxcursor1 libgl1-mesa-glx procps wget
    - conda config --set always_yes yes --set changeps1 no
  script:
    - source activate base
    - conda install mamba=$MAMBA_VERSION -c conda-forge
    - echo $CONDARC >> ~/.condarc
    - conda config --add channels "file://`pwd`/bld-dir"
    - mamba create -n test python tttrconvert
    - conda activate test
    # Run GUI with xvfb - no X11 screen
    - |
      xvfb-run -a -s "-screen 0 1400x900x24 +extension RANDR" -- tttrconvert &
      sleep 10
      pgrep -f tttrconvert | awk '{print "kill -9 " $1}' | sh

deploy:
  stage: deploy
  image: continuumio/miniconda3:latest
  tags:
    - linux
  dependencies:
    - build:linux
  script:
    - source activate
    - conda install anaconda-client
    - if [[ "$CI_COMMIT_REF_NAME" == "master" ]]; then DEPLOY_LABEL=$LABEL_RELEASE; else DEPLOY_VARIABLE=$LABEL_TESTING; fi
    - anaconda -t ${ANACONDA_API_TOKEN} upload -l ${DEPLOY_VARIABLE} -u ${CONDA_USER} --force bld-dir/linux-64/*.tar.bz2
  
chisurf:
  stage: Trigger-cross-projects
  trigger: chisurf/chisurf

