stages:
  - build
  - test
  - deploy

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  MINICONDA_VERSION: "latest"

build:linux:
  stage: build
  tags:
    - linux
  image: continuumio/miniconda3:latest
  script:
    - echo "I am a build stage job for debian, running on docker using continuumio/miniconda3:latest image"
    - source activate
    - conda install mamba boa conda-verify -c conda-forge
    - mamba update -y -n base -c defaults --all
    - |
        conda config --add channels salilab
        conda config --add channels conda-forge
        conda config --add channels tpeulen
    - conda mambabuild conda-recipe --output-folder bld-dir
  artifacts:
    expire_in: 7 days
    paths:
      - bld-dir/

test:linux:
  variables:
    MINICONDA_OS: "Linux"
  stage: test
  tags:
    - linux
  image: continuumio/miniconda3:latest
  before_script:
    # Issue with OpenGL and X11 display
    # See: https://stackoverflow.com/questions/65675765/is-it-possible-to-run-x11-on-gitlab-ci
    # See: https://github.com/conda-forge/pygridgen-feedstock/issues/10
    # procps is used to grep the process by name to kill it when needed
    - export DEBIAN_FRONTEND=noninteractive
    - apt update -yq
    - apt install -yq xorg-dev libglu1-mesa libgl1-mesa-dev xvfb libxinerama1 libxcursor1 libgl1-mesa-glx procps wget
    - conda config --set always_yes yes --set changeps1 no
  script:
    - echo "I am a test stage job for debian, running on docker using continuumio/miniconda3:latest image"
    - source activate base
    - conda install mamba conda-verify -c conda-forge
    - |
        conda config --add channels salilab
        conda config --add channels conda-forge
        conda config --add channels tpeulen
        conda config --add channels "file://`pwd`/bld-dir"
    - mamba create -n test python=3.7 tttrconvert
    - conda activate test
    # Run GUI with xvfb - no X11 screen
    - |
      xvfb-run -a -s "-screen 0 1400x900x24 +extension RANDR" -- tttrconvert &
      sleep 10
      pgrep -f tttrconvert | awk '{print "kill -9 " $1}' | sh

deploy:
  stage: deploy
  image: continuumio/miniconda3:latest
  tags:
    - linux
  dependencies:
    - build:linux
  script:
    - echo "I am a depolyment stage job for debian, running on docker using continuumio/miniconda3:latest image"
    - source activate
    - conda install anaconda-client
    - if [[ "$CI_COMMIT_REF_NAME" == "master" ]]; then DEPLOY_VARIABLE=main; else DEPLOY_VARIABLE=nightly; fi
    - anaconda -t ${ANACONDA_API_TOKEN} upload -l ${DEPLOY_VARIABLE} -u ${CONDA_USER} --force bld-dir/linux-64/*.tar.bz2
