name: tttrconvert

channels:
  - defaults
  - tpeulen
  - salilab
  - conda-forge

dependencies:
  - python =3.7.3
  - numpy
  - pyyaml >=5.0.0
  - qtpy >=1.8.0
  - pyqt >=5.13.0|5.9.2.*|5.6.0.*
  - typing_extensions
  - tttrlib
