__name__ = "tttrconvert"
__author__ = "Thomas-Otavio Peulen"
__version__ = "0.0.1"
__copyright__ = "Copyright (C) 2021 Thomas-Otavio Peulen"
__credits__ = ["Thomas-Otavio Peulen"]
__maintainer__ = "Thomas-Otavio Peulen"
__email__ = "thomas@peulen.xyz"
__url__ = "https://gitlab.peulen.xyz/tpeulen/tttrconvert"
__license__ = 'GPL2.1'
__status__ = "Dev"
__description__ = """tttrconvert: a file convert for tttr files."""
__app_id__ = "F25DCFFA-1234-4643-BC4F-2C2A20495217"
LONG_DESCRIPTION = """tttrconvert: a file convert for tttr files."""
help_url = 'https://gitlab.peulen.xyz/tpeulen/tttrconvert'
update_url = 'https://gitlab.peulen.xyz/tpeulen/tttrconvert'
