{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
  path: ..

build:
  number: 0
  entry_points:
    {% for entry_point_type, entry_points in data.get("entry_points", dict()).items() -%}
    {% for entry_point in entry_points -%}
    - {{ entry_point }}
    {% endfor %}
    {% endfor %}

requirements:
  build:
    - python
    - numpy
    - setuptools
    - pyyaml
  host:
    - python
    - numpy
    - pyyaml
    - setuptools
  run:
    - python
    - numpy
    - pandas
    - pyyaml >=5.0.0
    - qtpy
    - pyqt
    - pyqtgraph
    - tttrlib

test:
  imports:
    - tttrconvert
  commands:
    - tttrconvert &        # [osx or linux]

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  license_file: LICENSE
  summary: CLSMviewer application (for ChiSurf)
  description: |
    {{ data.get('description') }}

extra:
  recipe-maintainers:
    - tpeulen
